### PR TITLE
async: Allow async/await syntax

### PR DESCRIPTION
**Pull request by alancnet**
image

### CODE REVIEW

**Comment by n-riesco** [comment]
Unfortunately, this approach breaks the definition of variables in the global context.

For example:

```js
// In[1]:
var myGlobal = 1;
await Promise.resolve();

// In[2]:
console.log(myGlobal); // outputs `undefined` instead of 1
```

**Comment by n-riesco** [comment]
~~You could achieve the same thing by enabling [--experimental-repl-await](https://nodejs.org/api/repl.html#repl_await_keyword).~~

**Comment by vmarkovtsev** [comment]
So my approach - https://github.com/n-riesco/nel/pull/11 - does not break the global context and is taken from `--experimental-repl-await`

**Comment by n-riesco** [comment]
Closed in favour of #11,

**Pull request closed without merging**
