### PR TITLE
Accept Promises in Evaluation

### PR DESCRIPTION
**Pull request by thalesmello**
This pull request implements the capability of awaiting promises to be solved
before the result can be consumed by Jupyter.

Adresses #6

### CODE REVIEW

**Comment by thalesmello** [comment]
@n-riesco I've solved the conflicts.

**Comment by thalesmello** [comment]
I couldn't make my implementation work on version 0.10.48, not even with custom Promise implementations.

I'm thinking maybe there is a bug in this particular node version that makes my implementation not work.

Could you take a look, @n-riesco ?=

**Comment by n-riesco** [comment]
I will take a more careful look another day..

Sorry for the brevity, but, for the time being, this is a quick review:
- [x] ~~Read https://github.com/n-riesco/nel/blob/master/CONTRIBUTING.md~~
- [ ] don't use Promises in node 0.10. Check if Promises are already defined, if they aren't, keep the previous behaviour.
- [x] ~~try to imitate the existing coding style (e.g. prefer `bind(this)` to `var self = this`)~~
- [x] ~~again, instead of `makeMimeSender(mimeBuilderOf("image/jpeg"))` use [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)~~
- [x] ~~move `log("RESULT:", message);` out of the Promise (we want to see the log message regardless of the promise resolution)~~
- [ ] limit your changes to execution requests; i.e. `onRunRequest`.

**Comment by thalesmello** [comment]
@n-riesco 
- Included name in authors
- How should I avoid using Promises for 0.1.0? The tests are supposed to run in every node version, right?
- I've changed the code to reflect the requests. Ended up much better, actually. Could you take a look, please?

**Comment by thalesmello** [comment]
@n-riesco I've managed to make the implementation work with Node 0.10.48

However, that was accomplished using Bluebird as a dependency for when the Promise implementation is not available.

I'm assuming this is okay. If there is particularly a dependency for this project not to have dependencies, a good alternative would be to use a lightweight Promise implementation in this situation.

What do you think about it?

**Comment by n-riesco** [comment]
I still feel this PR is more invasive than necessary.

I'm concerned that I'm making you spend too much time on this PR. If you feel so, I can merge the PR as is (to give you the due credit) and I'll make the remaining changes.

Here's the remaining things I'd like to change in this PR:

- [ ] Do not add a dependency on `bluebird`. Let the user choose a `Promise` implementation (if any). To be clear, what I'd like to see is:

  - check whether `Promise`'s are defined in a way compatible with Node v0.10; e.g `(typeof global.Promise === "function")`

  - and then check whether the execution result is a `Promise`; e.g. `(result instanceof global.Promise)`

- [ ] Only change the file `lib/server/context.js`. Changes to the other source files are unnecessary.

- [ ] I still feel unsure about `buildPropertyMime`. I understand your intentions, but the reason why I didn't refactor into a function the code in places like [here](https://github.com/n-riesco/nel/blob/d4c5f2c3d213f684a987e444b555a46e514bed46/lib/server/context.js#L108-L115) was:

  - readability: the class `Context` provides `Context#send` and the functions in lines like [here](https://github.com/n-riesco/nel/blob/d4c5f2c3d213f684a987e444b555a46e514bed46/lib/server/context.js#L108-L115) are so small, that I don't want to burden the person reading he code with undertanding when they need to use `Context#send` or `sendMime`.

  - another reason why I didn't want to refactor those functions is that in the future, I'd like to validate the input to these functions;

  The way I see this PR, you only need a wrapper for functions like `$$.text(output, keepAlive)`, that checks whether `output` is a `Promise`, if it is, it resolves the `Promise` before calling `$$.text`.


- [ ] Please, rewrite the tests so that they can run in environments without `Promise`'s. Also note that although the test `new Promise(function (resolve) { setTimeout(resolve) }).then(function () { return $$.jpeg(1) })` may pass, strictly speaking, it isn't correct. `$$` is associated with an execution cell, but asynchronous functions aren't. If you'd like to use `$$` inside an asynchronous function, first you need to make a copy. In this case, the test could be rewritten as `(function($$) { return (global.Promise) ? Promise.resolve().then(function() {$$.jpeg(1)}) : $$.jpeg(1); })($$);`

- [ ] The names in `AUTHORS` are listed alphabetically by first name.

- [ ] As a general rule, follow the coding style already present (the main thing I've noticed is the use of single quotes instead of double quotes).

I think that's all. As I said above, please, let me know if you want me to make the remaining changes. And thank you for all your work!

**Comment by n-riesco** [comment]
@thalesmello Would you be happy is I merge this PR as is and I make the necessary changes after?

**Comment by thalesmello** [comment]
@n-riesco

Hello. Sorry for the delay. I was waiting for some available time to work
on the project, but that's probably not going to happen soon.

It's probably best if you merge, so that you can keep your work on the
project.

Thanks for the attention and sorry I'm not able to help any further at this
time.

**Comment by n-riesco** [comment]
@thalesmello No worries and thanks for your work!

**Pull request merged**
